services:
  internship-db:
    image: postgres:16-alpine
    container_name: internship-db
    environment:
      POSTGRES_DB: internship_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - internship-data:/var/lib/postgresql/data
    networks:
      - modulo5-net

  document-db:
    image: mongo:7
    container_name: document-db
    ports:
      - "27017:27017"
    volumes:
      - document-data:/data/db
    networks:
      - modulo5-net

  internship-service:
    image: camaisincho/internship-service:latest
    container_name: internship-service
    expose:
      - "3001"
    depends_on:
      - internship-db
    environment:
      DB_HOST: internship-db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: pass
      DB_NAME: internship_db
    networks:
      - modulo5-net

  document-service:
    image: camaisincho/document-service:latest
    container_name: document-service
    expose:
      - "3002"
    depends_on:
      - document-db
    environment:
      MONGO_URI: mongodb://document-db:27017/document_db
    networks:
      - modulo5-net

  approval-workflow-db:
    image: postgres:16-alpine
    container_name: approval-workflow-db
    environment:
      POSTGRES_DB: approval_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5433:5432"
    volumes:
      - approval-data:/var/lib/postgresql/data
    networks:
      - modulo5-net

  approval-workflow:
    image: camaisincho/approval-workflow:latest
    container_name: approval-workflow
    expose:
      - "3003"
    depends_on:
      - approval-workflow-db
    environment:
      DB_HOST: approval-workflow-db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: pass
      DB_NAME: approval_db
    networks:
      - modulo5-net

  report-db:
    image: postgres:16-alpine
    container_name: report-db
    environment:
      POSTGRES_DB: report_hours_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5434:5432"
    volumes:
      - report-data:/var/lib/postgresql/data
    networks:
      - modulo5-net

  report-hours:
    build: ../apps/report-hours
    image: camaisincho/report-hours:latest
    container_name: report-hours
    expose:
      - "3004"
    depends_on:
      - report-db
    environment:
      DATABASE_URL: postgresql://user:pass@report-db:5432/report_hours_db
    networks:
      - modulo5-net

  api-gateway:
    build: ./nginx
    image: camaisincho/api-gateway:latest
    container_name: api-gateway
    ports:
      - "80:80"
    depends_on:
      - internship-service
      - document-service
      - approval-workflow
      - report-hours
    networks:
      - modulo5-net

volumes:
  internship-data:
  document-data:
  approval-data:
  report-data:

networks:
  modulo5-net:
    driver: bridge